#
# This file was generated by bqtinstaller.py (bazel qt installer)
# To update run: bazel run @//:qt_install_x86_64.update
#

QT_MODULES = {
    "qt3d": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.debug_info.gcc_64/6.4.0-0-202209270704qt3d-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64-debug-symbols.7z",
        "sha256": "f4e9b74cd3c7363c1ee42c66a65630703b63c2975cdb584c0ce66b4a13b242c8"
    },
    "qtcharts": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.debug_info.gcc_64/6.4.0-0-202209270704qtcharts-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64-debug-symbols.7z",
        "sha256": "465331748a4e37f85955676cd7286de4f11bc5549f76ab35e2c7c8d1da5ec44a"
    },
    "qtconnectivity": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.debug_info.gcc_64/6.4.0-0-202209270704qtconnectivity-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64-debug-symbols.7z",
        "sha256": "3326871757ba401660855cf006f39ba4dc878de29667e067877115ed56b5a024"
    },
    "qtdatavis3d": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.debug_info.gcc_64/6.4.0-0-202209270704qtdatavis3d-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64-debug-symbols.7z",
        "sha256": "6e8f7e21534314da4cfec5de82dff1c91da077fbd385178397c5aac70f78aa9f"
    },
    "qthttpserver": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.debug_info.gcc_64/6.4.0-0-202209270704qthttpserver-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64-debug-symbols.7z",
        "sha256": "18da1844e209cfd42010a9581984b804175d50f08ab0b03b51c4be661dc2a70a"
    },
    "qtimageformats": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.debug_info.gcc_64/6.4.0-0-202209270704qtimageformats-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64-debug-symbols.7z",
        "sha256": "5691634e730b7b132af453c94331433114dfee1d770bc565deba91be58dfd888"
    },
    "qtlanguageserver": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.debug_info.gcc_64/6.4.0-0-202209270704qtlanguageserver-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64-debug-symbols.7z",
        "sha256": "17b82db5264bdecd4d8d712700a7c6919a9ea8a63cf3d1ba36f93dbf64fe4717"
    },
    "qtlottie": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.debug_info.gcc_64/6.4.0-0-202209270704qtlottie-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64-debug-symbols.7z",
        "sha256": "16215235fd1dd1d46d1176394d21382b3e86c22efc7192333df53fa285826d49"
    },
    "qtmultimedia": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.debug_info.gcc_64/6.4.0-0-202209270704qtmultimedia-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64-debug-symbols.7z",
        "sha256": "07c4a05c8dbc85ca9bc65c1b791d30c51c1df341c85dff85b75653c335b0c5ad"
    },
    "qtnetworkauth": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.debug_info.gcc_64/6.4.0-0-202209270704qtnetworkauth-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64-debug-symbols.7z",
        "sha256": "e12056fcdd53b95f829816fe733a3c5f61b8eaf84ab9075ca71d66ff114554a1"
    },
    "qtpdf": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.addons.qtpdf.gcc_64/6.4.0-0-202209270704qtpdf-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z",
        "sha256": "055bf9f904e44a89ef6d9c540fd180e3854f8792045c147323c722f16f624eb6"
    },
    "qtpositioning": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.debug_info.gcc_64/6.4.0-0-202209270704qtpositioning-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64-debug-symbols.7z",
        "sha256": "7e8bad3049f25e6625be67465ee53819c1d9e457f28a3aa965c7f5017cb673e7"
    },
    "qtquick3dphysics": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.debug_info.gcc_64/6.4.0-0-202209270704qtquick3dphysics-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64-debug-symbols.7z",
        "sha256": "70cf31871c830298c689bed5aa5e07454fd0387bc21874346e18775a1992f126"
    },
    "qtremoteobjects": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.debug_info.gcc_64/6.4.0-0-202209270704qtremoteobjects-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64-debug-symbols.7z",
        "sha256": "e52404e1d7e5800b3235a8405dff3c585835336d515bf08fbd609cf941243d47"
    },
    "qtscxml": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.debug_info.gcc_64/6.4.0-0-202209270704qtscxml-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64-debug-symbols.7z",
        "sha256": "d2e987a738d5cc241c10d783840912a67ec4e28dba932491906302e1ee2c1108"
    },
    "qtsensors": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.debug_info.gcc_64/6.4.0-0-202209270704qtsensors-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64-debug-symbols.7z",
        "sha256": "ee9a064aebe65e108fb023d633e44b4f63f8a8d0db5e5bcaff6f19362ce5717f"
    },
    "qtserialbus": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.debug_info.gcc_64/6.4.0-0-202209270704qtserialbus-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64-debug-symbols.7z",
        "sha256": "74929eeb7dbcd487c1b6b1ef036ea16f81be4be83194e7f3b443bdeb1684df0e"
    },
    "qtserialport": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.debug_info.gcc_64/6.4.0-0-202209270704qtserialport-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64-debug-symbols.7z",
        "sha256": "7ce13286194cd87eec19627624bd0213d6026a56868339069c0a1839419d2e02"
    },
    "qtspeech": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.debug_info.gcc_64/6.4.0-0-202209270704qtspeech-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64-debug-symbols.7z",
        "sha256": "55abc8662aa95fe9aa92decfadad0fcb67fce5cfc20f54d277d4bbf15e073ebc"
    },
    "qtvirtualkeyboard": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.debug_info.gcc_64/6.4.0-0-202209270704qtvirtualkeyboard-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64-debug-symbols.7z",
        "sha256": "d546bd70825472696479195eda06f983235557a19e1a65cdf378d7f2c92c4369"
    },
    "qtwebchannel": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.debug_info.gcc_64/6.4.0-0-202209270704qtwebchannel-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64-debug-symbols.7z",
        "sha256": "94ef58720e01ecf5b045d8d01092b248753de4f15047fe487d4c8b6627248c33"
    },
    "qtwebengine": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.debug_info.gcc_64/6.4.0-0-202209270704qtwebengine-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64-debug-symbols.7z",
        "sha256": "943b47044941f0b80c8c39fc7ed1d0e696adfadd747d4483cc54496897f5401c"
    },
    "qtwebsockets": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.debug_info.gcc_64/6.4.0-0-202209270704qtwebsockets-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64-debug-symbols.7z",
        "sha256": "ad4c3d092c9d90a093e85d1ea290b32bb49fb12c065d88527a51f059fe8b6c34"
    },
    "qtwebview": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.debug_info.gcc_64/6.4.0-0-202209270704qtwebview-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64-debug-symbols.7z",
        "sha256": "0e244a9069b3241d67b08fb436c274e4b81d0da4e4914ffc811d2410a843d3bc"
    },
    "qtbase": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.gcc_64/6.4.0-0-202209270704qtbase-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z",
        "sha256": "247952825916fab207d258c41ddf1a5c0ab0007c7c02940fa995a4ead5cc03ea"
    },
    "qtsvg": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.gcc_64/6.4.0-0-202209270704qtsvg-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z",
        "sha256": "96db59549864a205c83b0e4a7095c7d8a868af6930ce791f2df79b2fcb3245f1"
    },
    "qtdeclarative": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.gcc_64/6.4.0-0-202209270704qtdeclarative-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z",
        "sha256": "ffebc23f2afa5cb75b7d59f9b2b1bf28a7120bf2b16ead2ad32e49812b9cd8f8"
    },
    "qttools": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.gcc_64/6.4.0-0-202209270704qttools-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z",
        "sha256": "9c0eb05e86e129e38643af6fa17e5dfe75d5b49e8e1bbef2baa348066537efb7"
    },
    "qt5compat": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.qt5compat.gcc_64/6.4.0-0-202209270704qt5compat-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z",
        "sha256": "03d71fb047a5e1dc5fe80a633f8b628ebd75f0d6052931fb82c6a8c858b0cfbe"
    },
    "qtwayland": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.qtwaylandcompositor.gcc_64/6.4.0-0-202209270704qtwayland-compositor-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z",
        "sha256": "f902214a1ab83cfd5f1399ffefca9d45f1763b14acebcc2e0abcde279be98efb"
    },
    "qtshadertools": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.qtshadertools.gcc_64/6.4.0-0-202209270704qtshadertools-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z",
        "sha256": "23e7231917cee000350c85c3f7d6018df6f7a67ebe4ef3c0bbff51c69bbd118d"
    },
    "qtquick3d": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.qtquick3d.gcc_64/6.4.0-0-202209270704qtquick3d-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z",
        "sha256": "108c375d2c1b743f3cece096f7f256dc46a9b99f3bd6e70e8427e06ba4f5ed92"
    },
    "qtquicktimeline": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.qtquicktimeline.gcc_64/6.4.0-0-202209270704qtquicktimeline-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z",
        "sha256": "deeb73bcfae72a40676187058dab814ed8e8515f997176cf5a5f23d57c69ea46"
    },
    "qtcoap": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.debug_info.gcc_64/6.4.0-0-202209270704qtcoap-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64-debug-symbols.7z",
        "sha256": "50b3a66a4672d0ed1502650cdb6dab32f8f098c7db25276c7777909c5d34da2a"
    },
    "qtmqtt": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.debug_info.gcc_64/6.4.0-0-202209270704qtmqtt-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64-debug-symbols.7z",
        "sha256": "97ba74dd3e16db011561e1f61d7c61ca9fb2e7e0d73e3df72d593d2738c710ba"
    },
    "qtopcua": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.debug_info.gcc_64/6.4.0-0-202209270704qtopcua-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64-debug-symbols.7z",
        "sha256": "31ca6ce66f8cca146524ce94206706754e15c80af1a01ba8323608204e6d2438"
    },
    "qttranslations": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.gcc_64/6.4.0-0-202209270704qttranslations-Linux-RHEL_8_4-GCC-Linux-RHEL_8_4-X86_64.7z",
        "sha256": "72a644c4e6de3bdcbb8e85b8790b10858405c876ba19feac95a5b5087b72da18"
    },
    "icu": {
        "url": "https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_640/qt.qt6.640.gcc_64/6.4.0-0-202209270704icu-linux-Rhel7.2-x64.7z",
        "sha256": "2ca8e8fb1af43cfd654bf89f82b1cc8d3d7bcb30db52ee0181231f7a2692a5d3"
    }
}